### ISSUE TITLE
DeprecationWarning: loaderUtils.parseQuery() received a non-string value

### ISSUE THREAD

**Issue by epihel** [theplatapi/csv-loader#4]
Using node 7.7.4, webpack 2.2.1, and csv-loader 2.0.4, CSV files are successfully loaded, but with this deprecation warning:

(node:18879) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
    at Object.parseQuery (/node_modules/loader-utils/index.js:78:3)
    at Object.exports.getLoaderConfig (/node_modules/loader-utils/index.js:121:22)
    at Object.module.exports (/node_modules/csv-loader/index.js:6:28)
    at LOADER_EXECUTION (/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at Array.<anonymous> (/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
    at Storage.finished (/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:15)
    at /node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:69:9
    at /node_modules/graceful-fs/graceful-fs.js:78:16

**Comment by theplatapi** [comment]
Thanks for pointing this out. Does `2.1.0` remove the warning for you?

**Comment by epihel** [comment]
Yes; the warning is gone after upgrading to 2.1.0. Thanks!
